services:
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ../minio-data:/data
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark-base
    develop:
      watch:
        - path: ./Dockerfile.spark-base
          action: rebuild
    container_name: spark-master
    hostname: spark-master
    # depends_on:
    #   - minio
    command: >
      /opt/spark/sbin/start-master.sh &&
      tail -f /dev/null
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_NO_DAEMONIZE: "true"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.spark-base
    develop:
      watch:
        - path: ./Dockerfile.spark-base
          action: rebuild
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    command: >
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
    ports:
      - "8081:8081"
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "1g"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.spark-base
    develop:
      watch:
        - path: ./Dockerfile.spark-base
          action: rebuild
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    command: >
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
    ports:
      - "8082:8081"
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "1g"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    develop:
      watch:
        - path: ./Dockerfile.jupyter
          action: rebuild
    container_name: jupyter
    hostname: jupyter
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../jupyter-data:/home/jovyan/data
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
      SPARK_MASTER: spark://spark-master:7077
      PYSPARK_SUBMIT_ARGS: >
        --master spark://spark-master:7077
        --conf spark.driver.host=jupyter
        --conf spark.driver.extraJavaOptions="-Dderby.system.home=/tmp"
        --conf spark.hadoop.fs.s3a.endpoint="http://minio:9000"
        --conf spark.hadoop.fs.s3a.access.key="minio"
        --conf spark.hadoop.fs.s3a.secret.key="minio123"
        --conf spark.hadoop.fs.s3a.path.style.access="true"
        --conf spark.hadoop.fs.s3a.connection.ssl.enabled="false"
        --conf spark.hadoop.fs.s3a.impl="org.apache.hadoop.fs.s3a.S3AFileSystem"
        --conf spark.sql.warehouse.dir="s3a://warehouse/"
        pyspark-shell
